services:
  - type: web
    name: netraai-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn api_neo4j:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
